all:
  hosts: {}
  children:
    illuminati:
      hosts:
        illum00: {}
    gluster:
      hosts:
        gluster-c7-00: {}
        gluster-c7-01: {}
        gluster-c7-02: {}
        gluster-c7-03: {}
